services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    volumes:
      - ./web:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - ml

  ml:
    build:
      context: ./recommendation_system
      dockerfile: Dockerfile.dev
    volumes:
      - ./recommendation_system:/app
    ports:
      - "8000:8000"
