services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - ml

  ml:
    build:
      context: ./recommendation_system
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
